#!/usr/bin/env python
import os
from os import path

KEY_PATH = "keys/"

for file in os.listdir(KEY_PATH):
	if path.isdir(KEY_PATH + file):
		os.system("./create_or_renew %s" % file)

print "Reloading nginx..."
os.system('service nginx reload')

